package org.omg.IOP;


/**
* org/omg/IOP/RMICustomMaxStreamFormat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/Zulu/zulu-platform-build/58942/zulu-src.git/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Friday, April 11, 2025 8:41:07 AM UTC
*/

public interface RMICustomMaxStreamFormat
{

  /**
     * Identifies a CDR encapsulation of the RMICustomMaxStreamFormat
     * service context which contains a single byte specifying
     * the client's maximum RMI-IIOP stream format version.
     *
     * See Java to IDL ptc/02-01-12 1.4.12.
     */
  public static final int value = (int)(17L);
}
