package org.omg.IOP;


/**
* org/omg/IOP/CodeSets.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/Zulu/zulu-platform-build/58942/zulu-src.git/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Friday, April 11, 2025 8:41:07 AM UTC
*/

public interface CodeSets
{

  /**
     * Identifies a CDR encapsulation of the 
     * <code>CONV_FRAME.CodeSetContext</code> defined in 
     * Section 13.10.2.5, "GIOP Code Set Service Context," on page 13-43.
     */
  public static final int value = (int)(1L);
}
