package org.omg.Messaging;


/**
* org/omg/Messaging/SYNC_WITH_TRANSPORT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/Zulu/zulu-platform-build/58942/zulu-src.git/corba/src/share/classes/org/omg/PortableInterceptor/Messaging.idl
* Friday, April 11, 2025 8:41:07 AM UTC
*/

public interface SYNC_WITH_TRANSPORT
{

  /**
   * Constant, defined in the Messaging spec, to define how far the 
   * request shall progress before control is returned to the client.
   */
  public static final short value = (short)(1);
}
