package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/IIOP_CLEAR_TEXT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/Zulu/zulu-platform-build/58942/zulu-src.git/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Friday, April 11, 2025 8:41:07 AM UTC
*/

public interface IIOP_CLEAR_TEXT
{

  // to avoid a compilation dependency.
  public static final String value = "IIOP_CLEAR_TEXT";
}
