package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/Locator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/Zulu/zulu-platform-build/58942/zulu-src.git/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Friday, April 11, 2025 8:41:07 AM UTC
*/

public interface Locator extends LocatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Locator
