package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/HOLDING.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/jenkins/workspace/Zulu/zulu-platform-build/58942/zulu-src.git/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Friday, April 11, 2025 8:41:07 AM UTC
*/

public interface HOLDING
{

  /** Object adapter state that holds requests temporarily until the 
   * state is changed.
   */
  public static final short value = (short)(0);
}
